// This file was automatically generated by Biohazrd and should not be modified by hand!
#include "../external/imgui/imgui.h"
#include "../external/imgui/imgui_internal.h"

namespace ____BiohazrdInlineExportHelpers
{
#pragma GCC visibility push(hidden)
    float (ImVec2::* unused0)(unsigned long) const = &ImVec2::operator[];
    float & (ImVec2::* unused1)(unsigned long) = &ImVec2::operator[];
    void (ImGuiInputTextCallbackData::* unused2)() = &ImGuiInputTextCallbackData::SelectAll;
    void (ImGuiInputTextCallbackData::* unused3)() = &ImGuiInputTextCallbackData::ClearSelection;
    bool (ImGuiInputTextCallbackData::* unused4)() const = &ImGuiInputTextCallbackData::HasSelection;
    void (ImGuiPayload::* unused5)() = &ImGuiPayload::Clear;
    bool (ImGuiPayload::* unused6)(const char *) const = &ImGuiPayload::IsDataType;
    bool (ImGuiPayload::* unused7)() const = &ImGuiPayload::IsPreview;
    bool (ImGuiPayload::* unused8)() const = &ImGuiPayload::IsDelivery;
    bool (ImGuiOnceUponAFrame::* unused9)() const = &ImGuiOnceUponAFrame::operator bool;
    void (ImGuiTextFilter::* unused10)() = &ImGuiTextFilter::Clear;
    bool (ImGuiTextFilter::* unused11)() const = &ImGuiTextFilter::IsActive;
    bool (ImGuiTextFilter::ImGuiTextRange::* unused12)() const = &ImGuiTextFilter::ImGuiTextRange::empty;
    char (ImGuiTextBuffer::* unused13)(int) const = &ImGuiTextBuffer::operator[];
    const char * (ImGuiTextBuffer::* unused14)() const = &ImGuiTextBuffer::begin;
    const char * (ImGuiTextBuffer::* unused15)() const = &ImGuiTextBuffer::end;
    int (ImGuiTextBuffer::* unused16)() const = &ImGuiTextBuffer::size;
    bool (ImGuiTextBuffer::* unused17)() const = &ImGuiTextBuffer::empty;
    void (ImGuiTextBuffer::* unused18)() = &ImGuiTextBuffer::clear;
    void (ImGuiTextBuffer::* unused19)(int) = &ImGuiTextBuffer::reserve;
    const char * (ImGuiTextBuffer::* unused20)() const = &ImGuiTextBuffer::c_str;
    void (ImGuiStorage::* unused21)() = &ImGuiStorage::Clear;
    unsigned int (ImColor::* unused22)() const = &ImColor::operator unsigned int;
    ImVec4 (ImColor::* unused23)() const = &ImColor::operator ImVec4;
    void (ImColor::* unused24)(float, float, float, float) = &ImColor::SetHSV;
    ImColor (*unused25)(float, float, float, float) = &ImColor::HSV;
    void (ImDrawListSplitter::* unused26)() = &ImDrawListSplitter::Clear;
    ImVec2 (ImDrawList::* unused27)() const = &ImDrawList::GetClipRectMin;
    ImVec2 (ImDrawList::* unused28)() const = &ImDrawList::GetClipRectMax;
    void (ImDrawList::* unused29)() = &ImDrawList::PathClear;
    void (ImDrawList::* unused30)(const ImVec2 &) = &ImDrawList::PathLineTo;
    void (ImDrawList::* unused31)(const ImVec2 &) = &ImDrawList::PathLineToMergeDuplicate;
    void (ImDrawList::* unused32)(unsigned int) = &ImDrawList::PathFillConvex;
    void (ImDrawList::* unused33)(unsigned int, bool, float) = &ImDrawList::PathStroke;
    void (ImDrawList::* unused34)(int) = &ImDrawList::ChannelsSplit;
    void (ImDrawList::* unused35)() = &ImDrawList::ChannelsMerge;
    void (ImDrawList::* unused36)(int) = &ImDrawList::ChannelsSetCurrent;
    void (ImDrawList::* unused37)(const ImVec2 &, const ImVec2 &, unsigned int) = &ImDrawList::PrimWriteVtx;
    void (ImDrawList::* unused38)(unsigned short) = &ImDrawList::PrimWriteIdx;
    void (ImDrawList::* unused39)(const ImVec2 &, const ImVec2 &, unsigned int) = &ImDrawList::PrimVtx;
    void (ImDrawData::* unused40)() = &ImDrawData::Clear;
    void (ImFontGlyphRangesBuilder::* unused41)() = &ImFontGlyphRangesBuilder::Clear;
    bool (ImFontGlyphRangesBuilder::* unused42)(unsigned long) const = &ImFontGlyphRangesBuilder::GetBit;
    void (ImFontGlyphRangesBuilder::* unused43)(unsigned long) = &ImFontGlyphRangesBuilder::SetBit;
    void (ImFontGlyphRangesBuilder::* unused44)(unsigned short) = &ImFontGlyphRangesBuilder::AddChar;
    bool (ImFontAtlasCustomRect::* unused45)() const = &ImFontAtlasCustomRect::IsPacked;
    bool (ImFontAtlas::* unused46)() const = &ImFontAtlas::IsBuilt;
    void (ImFontAtlas::* unused47)(void *) = &ImFontAtlas::SetTexID;
    ImFontAtlasCustomRect * (ImFontAtlas::* unused48)(int) = &ImFontAtlas::GetCustomRectByIndex;
    float (ImFont::* unused49)(unsigned short) const = &ImFont::GetCharAdvance;
    bool (ImFont::* unused50)() const = &ImFont::IsLoaded;
    const char * (ImFont::* unused51)() const = &ImFont::GetDebugName;
    ImVec2 (ImGuiViewport::* unused52)() const = &ImGuiViewport::GetCenter;
    ImVec2 (ImGuiViewport::* unused53)() const = &ImGuiViewport::GetWorkCenter;
    ImVec2 (ImRect::* unused54)() const = &ImRect::GetCenter;
    ImVec2 (ImRect::* unused55)() const = &ImRect::GetSize;
    float (ImRect::* unused56)() const = &ImRect::GetWidth;
    float (ImRect::* unused57)() const = &ImRect::GetHeight;
    ImVec2 (ImRect::* unused58)() const = &ImRect::GetTL;
    ImVec2 (ImRect::* unused59)() const = &ImRect::GetTR;
    ImVec2 (ImRect::* unused60)() const = &ImRect::GetBL;
    ImVec2 (ImRect::* unused61)() const = &ImRect::GetBR;
    bool (ImRect::* unused62)(const ImVec2 &) const = &ImRect::Contains;
    bool (ImRect::* unused63)(const ImRect &) const = &ImRect::Contains;
    bool (ImRect::* unused64)(const ImRect &) const = &ImRect::Overlaps;
    void (ImRect::* unused65)(const ImVec2 &) = &ImRect::Add;
    void (ImRect::* unused66)(const ImRect &) = &ImRect::Add;
    void (ImRect::* unused67)(const float) = &ImRect::Expand;
    void (ImRect::* unused68)(const ImVec2 &) = &ImRect::Expand;
    void (ImRect::* unused69)(const ImVec2 &) = &ImRect::Translate;
    void (ImRect::* unused70)(float) = &ImRect::TranslateX;
    void (ImRect::* unused71)(float) = &ImRect::TranslateY;
    void (ImRect::* unused72)(const ImRect &) = &ImRect::ClipWith;
    void (ImRect::* unused73)(const ImRect &) = &ImRect::ClipWithFull;
    void (ImRect::* unused74)() = &ImRect::Floor;
    bool (ImRect::* unused75)() const = &ImRect::IsInverted;
    ImVec4 (ImRect::* unused76)() const = &ImRect::ToVec4;
    void (ImBitVector::* unused77)(int) = &ImBitVector::Create;
    void (ImBitVector::* unused78)() = &ImBitVector::Clear;
    bool (ImBitVector::* unused79)(int) const = &ImBitVector::TestBit;
    void (ImBitVector::* unused80)(int) = &ImBitVector::SetBit;
    void (ImBitVector::* unused81)(int) = &ImBitVector::ClearBit;
    void (ImDrawDataBuilder::* unused82)() = &ImDrawDataBuilder::Clear;
    void (ImDrawDataBuilder::* unused83)() = &ImDrawDataBuilder::ClearFreeMemory;
    int (ImDrawDataBuilder::* unused84)() const = &ImDrawDataBuilder::GetDrawListCount;
    void (ImGuiInputTextState::* unused85)() = &ImGuiInputTextState::ClearText;
    void (ImGuiInputTextState::* unused86)() = &ImGuiInputTextState::ClearFreeMemory;
    int (ImGuiInputTextState::* unused87)() const = &ImGuiInputTextState::GetUndoAvailCount;
    int (ImGuiInputTextState::* unused88)() const = &ImGuiInputTextState::GetRedoAvailCount;
    void (ImGuiInputTextState::* unused89)() = &ImGuiInputTextState::CursorAnimReset;
    void (ImGuiInputTextState::* unused90)() = &ImGuiInputTextState::CursorClamp;
    bool (ImGuiInputTextState::* unused91)() const = &ImGuiInputTextState::HasSelection;
    void (ImGuiInputTextState::* unused92)() = &ImGuiInputTextState::ClearSelection;
    void (ImGuiInputTextState::* unused93)() = &ImGuiInputTextState::SelectAll;
    void (ImGuiNavMoveResult::* unused94)() = &ImGuiNavMoveResult::Clear;
    void (ImGuiNextWindowData::* unused95)() = &ImGuiNextWindowData::ClearFlags;
    void (ImGuiNextItemData::* unused96)() = &ImGuiNextItemData::ClearFlags;
    bool (ImGuiDockNode::* unused97)() const = &ImGuiDockNode::IsRootNode;
    bool (ImGuiDockNode::* unused98)() const = &ImGuiDockNode::IsDockSpace;
    bool (ImGuiDockNode::* unused99)() const = &ImGuiDockNode::IsFloatingNode;
    bool (ImGuiDockNode::* unused100)() const = &ImGuiDockNode::IsCentralNode;
    bool (ImGuiDockNode::* unused101)() const = &ImGuiDockNode::IsHiddenTabBar;
    bool (ImGuiDockNode::* unused102)() const = &ImGuiDockNode::IsNoTabBar;
    bool (ImGuiDockNode::* unused103)() const = &ImGuiDockNode::IsSplitNode;
    bool (ImGuiDockNode::* unused104)() const = &ImGuiDockNode::IsLeafNode;
    bool (ImGuiDockNode::* unused105)() const = &ImGuiDockNode::IsEmpty;
    int (ImGuiDockNode::* unused106)() const = &ImGuiDockNode::GetMergedFlags;
    ImRect (ImGuiDockNode::* unused107)() const = &ImGuiDockNode::Rect;
    ImRect (ImGuiViewportP::* unused108)() const = &ImGuiViewportP::GetMainRect;
    ImRect (ImGuiViewportP::* unused109)() const = &ImGuiViewportP::GetWorkRect;
    void (ImGuiViewportP::* unused110)() = &ImGuiViewportP::UpdateWorkRect;
    void (ImGuiViewportP::* unused111)() = &ImGuiViewportP::ClearRequestFlags;
    char * (ImGuiWindowSettings::* unused112)() = &ImGuiWindowSettings::GetName;
    ImRect (ImGuiWindow::* unused113)() const = &ImGuiWindow::Rect;
    float (ImGuiWindow::* unused114)() const = &ImGuiWindow::CalcFontSize;
    float (ImGuiWindow::* unused115)() const = &ImGuiWindow::TitleBarHeight;
    ImRect (ImGuiWindow::* unused116)() const = &ImGuiWindow::TitleBarRect;
    float (ImGuiWindow::* unused117)() const = &ImGuiWindow::MenuBarHeight;
    ImRect (ImGuiWindow::* unused118)() const = &ImGuiWindow::MenuBarRect;
    void (ImGuiLastItemDataBackup::* unused119)() = &ImGuiLastItemDataBackup::Backup;
    void (ImGuiLastItemDataBackup::* unused120)() const = &ImGuiLastItemDataBackup::Restore;
    int (ImGuiTabBar::* unused121)(const ImGuiTabItem *) const = &ImGuiTabBar::GetTabOrder;
    const char * (ImGuiTabBar::* unused122)(const ImGuiTabItem *) const = &ImGuiTabBar::GetTabName;
    ImGuiTableColumnSettings * (ImGuiTableSettings::* unused123)() = &ImGuiTableSettings::GetColumnSettings;
    void * (*unused124)(unsigned long, ImNewWrapper, void *) = &operator new;
    void (*unused125)(void *, ImNewWrapper, void *) = &operator delete;
    float (*unused126)(const ImVec2 &, const ImVec2 &, const ImVec2 &) = &ImTriangleArea;
    bool (*unused127)(const unsigned int *, int) = &ImBitArrayTestBit;
    void (*unused128)(unsigned int *, int) = &ImBitArrayClearBit;
    void (*unused129)(unsigned int *, int) = &ImBitArraySetBit;
    void (*unused130)(unsigned int *, int, int) = &ImBitArraySetBitRange;
    ImGuiWindow * (*unused131)() = &ImGui::GetCurrentWindowRead;
    ImGuiWindow * (*unused132)() = &ImGui::GetCurrentWindow;
    ImFont * (*unused133)() = &ImGui::GetDefaultFont;
    ImDrawList * (*unused134)(ImGuiWindow *) = &ImGui::GetForegroundDrawList;
    unsigned int (*unused135)() = &ImGui::GetItemID;
    int (*unused136)() = &ImGui::GetItemStatusFlags;
    unsigned int (*unused137)() = &ImGui::GetActiveID;
    unsigned int (*unused138)() = &ImGui::GetFocusID;
    int (*unused139)() = &ImGui::GetItemsFlags;
    unsigned int (*unused140)() = &ImGui::GetFocusedFocusScope;
    unsigned int (*unused141)() = &ImGui::GetFocusScope;
    bool (*unused142)(int) = &ImGui::IsActiveIdUsingNavDir;
    bool (*unused143)(int) = &ImGui::IsActiveIdUsingNavInput;
    bool (*unused144)(int) = &ImGui::IsActiveIdUsingKey;
    bool (*unused145)(int, bool) = &ImGui::IsKeyPressedMap;
    bool (*unused146)(int) = &ImGui::IsNavInputDown;
    bool (*unused147)(int, ImGuiInputReadMode) = &ImGui::IsNavInputTest;
    ImGuiDockNode * (*unused148)(ImGuiDockNode *) = &ImGui::DockNodeGetRootNode;
    int (*unused149)(const ImGuiDockNode *) = &ImGui::DockNodeGetDepth;
    ImGuiDockNode * (*unused150)() = &ImGui::GetWindowDockNode;
    ImGuiDockNode * (*unused151)(unsigned int) = &ImGui::DockBuilderGetCentralNode;
    ImGuiTable * (*unused152)() = &ImGui::GetCurrentTable;
    bool (*unused153)(unsigned int) = &ImGui::TempInputIsActive;
    ImGuiInputTextState * (*unused154)(unsigned int) = &ImGui::GetInputTextState;
    void (*unused155)(unsigned int) = &ImGui::DebugDrawItemRect;
    void (*unused156)() = &ImGui::DebugStartItemPicker;
#pragma GCC visibility pop
}

namespace ____BiohazrdInlineExportHelpers
{
    struct __BiohazrdNewHelper { };
}

inline void* operator new(size_t, ____BiohazrdInlineExportHelpers::__BiohazrdNewHelper, void* _this) { return _this; }
inline void operator delete(void*, ____BiohazrdInlineExportHelpers::__BiohazrdNewHelper, void*) { }

#pragma warning(disable: 4190) // C-linkage function returning C++ type
extern "C" namespace ____BiohazrdInlineExportHelpers
{
#pragma GCC visibility push(default)

    ImVec2* __InlineHelper0(ImVec2* _this)
    { return new (__BiohazrdNewHelper(), _this) ImVec2(); }

    ImVec2* __InlineHelper1(ImVec2* _this, float _0, float _1)
    { return new (__BiohazrdNewHelper(), _this) ImVec2(_0, _1); }

    ImVec4* __InlineHelper2(ImVec4* _this)
    { return new (__BiohazrdNewHelper(), _this) ImVec4(); }

    ImVec4* __InlineHelper3(ImVec4* _this, float _0, float _1, float _2, float _3)
    { return new (__BiohazrdNewHelper(), _this) ImVec4(_0, _1, _2, _3); }

    ImGuiWindowClass* __InlineHelper4(ImGuiWindowClass* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiWindowClass(); }

    ImGuiPayload* __InlineHelper5(ImGuiPayload* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiPayload(); }

    ImGuiTableColumnSortSpecs* __InlineHelper6(ImGuiTableColumnSortSpecs* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTableColumnSortSpecs(); }

    ImGuiTableSortSpecs* __InlineHelper7(ImGuiTableSortSpecs* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTableSortSpecs(); }

    ImGuiOnceUponAFrame* __InlineHelper8(ImGuiOnceUponAFrame* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiOnceUponAFrame(); }

    ImGuiTextFilter::ImGuiTextRange* __InlineHelper9(ImGuiTextFilter::ImGuiTextRange* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTextFilter::ImGuiTextRange(); }

    ImGuiTextFilter::ImGuiTextRange* __InlineHelper10(ImGuiTextFilter::ImGuiTextRange* _this, const char *_0, const char *_1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTextFilter::ImGuiTextRange(_0, _1); }

    ImGuiTextBuffer* __InlineHelper11(ImGuiTextBuffer* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTextBuffer(); }

    ImGuiStorage::ImGuiStoragePair* __InlineHelper12(ImGuiStorage::ImGuiStoragePair* _this, unsigned int _0, int _1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStorage::ImGuiStoragePair(_0, _1); }

    ImGuiStorage::ImGuiStoragePair* __InlineHelper13(ImGuiStorage::ImGuiStoragePair* _this, unsigned int _0, float _1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStorage::ImGuiStoragePair(_0, _1); }

    ImGuiStorage::ImGuiStoragePair* __InlineHelper14(ImGuiStorage::ImGuiStoragePair* _this, unsigned int _0, void *_1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStorage::ImGuiStoragePair(_0, _1); }

    ImColor* __InlineHelper15(ImColor* _this)
    { return new (__BiohazrdNewHelper(), _this) ImColor(); }

    ImColor* __InlineHelper16(ImColor* _this, int _0, int _1, int _2, int _3)
    { return new (__BiohazrdNewHelper(), _this) ImColor(_0, _1, _2, _3); }

    ImColor* __InlineHelper17(ImColor* _this, unsigned int _0)
    { return new (__BiohazrdNewHelper(), _this) ImColor(_0); }

    ImColor* __InlineHelper18(ImColor* _this, float _0, float _1, float _2, float _3)
    { return new (__BiohazrdNewHelper(), _this) ImColor(_0, _1, _2, _3); }

    ImColor* __InlineHelper19(ImColor* _this, const ImVec4 &_0)
    { return new (__BiohazrdNewHelper(), _this) ImColor(_0); }

    ImDrawCmd* __InlineHelper20(ImDrawCmd* _this)
    { return new (__BiohazrdNewHelper(), _this) ImDrawCmd(); }

    ImDrawListSplitter* __InlineHelper21(ImDrawListSplitter* _this)
    { return new (__BiohazrdNewHelper(), _this) ImDrawListSplitter(); }

    void __InlineHelper22(ImDrawListSplitter* _this)
    { _this->~ImDrawListSplitter(); }

    ImDrawList* __InlineHelper23(ImDrawList* _this, const ImDrawListSharedData *_0)
    { return new (__BiohazrdNewHelper(), _this) ImDrawList(_0); }

    void __InlineHelper24(ImDrawList* _this)
    { _this->~ImDrawList(); }

    ImDrawData* __InlineHelper25(ImDrawData* _this)
    { return new (__BiohazrdNewHelper(), _this) ImDrawData(); }

    ImFontGlyphRangesBuilder* __InlineHelper26(ImFontGlyphRangesBuilder* _this)
    { return new (__BiohazrdNewHelper(), _this) ImFontGlyphRangesBuilder(); }

    ImFontAtlasCustomRect* __InlineHelper27(ImFontAtlasCustomRect* _this)
    { return new (__BiohazrdNewHelper(), _this) ImFontAtlasCustomRect(); }

    ImGuiViewport* __InlineHelper28(ImGuiViewport* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiViewport(); }

    void __InlineHelper29(ImGuiViewport* _this)
    { _this->~ImGuiViewport(); }

    ImGuiPlatformIO* __InlineHelper30(ImGuiPlatformIO* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiPlatformIO(); }

    ImGuiPlatformMonitor* __InlineHelper31(ImGuiPlatformMonitor* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiPlatformMonitor(); }

    ImVec1* __InlineHelper32(ImVec1* _this)
    { return new (__BiohazrdNewHelper(), _this) ImVec1(); }

    ImVec1* __InlineHelper33(ImVec1* _this, float _0)
    { return new (__BiohazrdNewHelper(), _this) ImVec1(_0); }

    ImVec2ih* __InlineHelper34(ImVec2ih* _this)
    { return new (__BiohazrdNewHelper(), _this) ImVec2ih(); }

    ImVec2ih* __InlineHelper35(ImVec2ih* _this, short _0, short _1)
    { return new (__BiohazrdNewHelper(), _this) ImVec2ih(_0, _1); }

    ImVec2ih* __InlineHelper36(ImVec2ih* _this, const ImVec2 &_0)
    { return new (__BiohazrdNewHelper(), _this) ImVec2ih(_0); }

    ImRect* __InlineHelper37(ImRect* _this)
    { return new (__BiohazrdNewHelper(), _this) ImRect(); }

    ImRect* __InlineHelper38(ImRect* _this, const ImVec2 &_0, const ImVec2 &_1)
    { return new (__BiohazrdNewHelper(), _this) ImRect(_0, _1); }

    ImRect* __InlineHelper39(ImRect* _this, const ImVec4 &_0)
    { return new (__BiohazrdNewHelper(), _this) ImRect(_0); }

    ImRect* __InlineHelper40(ImRect* _this, float _0, float _1, float _2, float _3)
    { return new (__BiohazrdNewHelper(), _this) ImRect(_0, _1, _2, _3); }

    ImGuiStyleMod* __InlineHelper41(ImGuiStyleMod* _this, int _0, int _1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStyleMod(_0, _1); }

    ImGuiStyleMod* __InlineHelper42(ImGuiStyleMod* _this, int _0, float _1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStyleMod(_0, _1); }

    ImGuiStyleMod* __InlineHelper43(ImGuiStyleMod* _this, int _0, ImVec2 _1)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStyleMod(_0, _1); }

    ImGuiMenuColumns* __InlineHelper44(ImGuiMenuColumns* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiMenuColumns(); }

    ImGuiInputTextState* __InlineHelper45(ImGuiInputTextState* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiInputTextState(); }

    ImGuiPopupData* __InlineHelper46(ImGuiPopupData* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiPopupData(); }

    ImGuiNavMoveResult* __InlineHelper47(ImGuiNavMoveResult* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiNavMoveResult(); }

    ImGuiNextWindowData* __InlineHelper48(ImGuiNextWindowData* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiNextWindowData(); }

    ImGuiNextItemData* __InlineHelper49(ImGuiNextItemData* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiNextItemData(); }

    ImGuiPtrOrIndex* __InlineHelper50(ImGuiPtrOrIndex* _this, void *_0)
    { return new (__BiohazrdNewHelper(), _this) ImGuiPtrOrIndex(_0); }

    ImGuiPtrOrIndex* __InlineHelper51(ImGuiPtrOrIndex* _this, int _0)
    { return new (__BiohazrdNewHelper(), _this) ImGuiPtrOrIndex(_0); }

    ImGuiOldColumnData* __InlineHelper52(ImGuiOldColumnData* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiOldColumnData(); }

    ImGuiOldColumns* __InlineHelper53(ImGuiOldColumns* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiOldColumns(); }

    ImGuiDockContext* __InlineHelper54(ImGuiDockContext* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiDockContext(); }

    ImGuiViewportP* __InlineHelper55(ImGuiViewportP* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiViewportP(); }

    void __InlineHelper56(ImGuiViewportP* _this)
    { _this->~ImGuiViewportP(); }

    ImGuiWindowSettings* __InlineHelper57(ImGuiWindowSettings* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiWindowSettings(); }

    ImGuiSettingsHandler* __InlineHelper58(ImGuiSettingsHandler* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiSettingsHandler(); }

    ImGuiMetricsConfig* __InlineHelper59(ImGuiMetricsConfig* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiMetricsConfig(); }

    ImGuiStackSizes* __InlineHelper60(ImGuiStackSizes* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiStackSizes(); }

    ImGuiContextHook* __InlineHelper61(ImGuiContextHook* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiContextHook(); }

    ImGuiContext* __InlineHelper62(ImGuiContext* _this, ImFontAtlas *_0)
    { return new (__BiohazrdNewHelper(), _this) ImGuiContext(_0); }

    ImGuiLastItemDataBackup* __InlineHelper63(ImGuiLastItemDataBackup* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiLastItemDataBackup(); }

    ImGuiTabItem* __InlineHelper64(ImGuiTabItem* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTabItem(); }

    ImGuiTableColumn* __InlineHelper65(ImGuiTableColumn* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTableColumn(); }

    ImGuiTable* __InlineHelper66(ImGuiTable* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTable(); }

    void __InlineHelper67(ImGuiTable* _this)
    { _this->~ImGuiTable(); }

    ImGuiTableColumnSettings* __InlineHelper68(ImGuiTableColumnSettings* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTableColumnSettings(); }

    ImGuiTableSettings* __InlineHelper69(ImGuiTableSettings* _this)
    { return new (__BiohazrdNewHelper(), _this) ImGuiTableSettings(); }

    bool __InlineHelper70(int _0)
    { return ImIsPowerOfTwo(_0); }

    bool __InlineHelper71(unsigned long long _0)
    { return ImIsPowerOfTwo(_0); }

    int __InlineHelper72(int _0)
    { return ImUpperPowerOfTwo(_0); }

    bool __InlineHelper73(char _0)
    { return ImCharIsBlankA(_0); }

    bool __InlineHelper74(unsigned int _0)
    { return ImCharIsBlankW(_0); }

    float __InlineHelper75(float _0, float _1)
    { return ImPow(_0, _1); }

    double __InlineHelper76(double _0, double _1)
    { return ImPow(_0, _1); }

    float __InlineHelper77(float _0)
    { return ImLog(_0); }

    double __InlineHelper78(double _0)
    { return ImLog(_0); }

    float __InlineHelper79(float _0)
    { return ImAbs(_0); }

    double __InlineHelper80(double _0)
    { return ImAbs(_0); }

    float __InlineHelper81(float _0)
    { return ImSign(_0); }

    double __InlineHelper82(double _0)
    { return ImSign(_0); }

    ImVec2 __InlineHelper83(const ImVec2 &_0, const ImVec2 &_1)
    { return ImMin(_0, _1); }

    ImVec2 __InlineHelper84(const ImVec2 &_0, const ImVec2 &_1)
    { return ImMax(_0, _1); }

    ImVec2 __InlineHelper85(const ImVec2 &_0, const ImVec2 &_1, ImVec2 _2)
    { return ImClamp(_0, _1, _2); }

    ImVec2 __InlineHelper86(const ImVec2 &_0, const ImVec2 &_1, float _2)
    { return ImLerp(_0, _1, _2); }

    ImVec2 __InlineHelper87(const ImVec2 &_0, const ImVec2 &_1, const ImVec2 &_2)
    { return ImLerp(_0, _1, _2); }

    ImVec4 __InlineHelper88(const ImVec4 &_0, const ImVec4 &_1, float _2)
    { return ImLerp(_0, _1, _2); }

    float __InlineHelper89(float _0)
    { return ImSaturate(_0); }

    float __InlineHelper90(const ImVec2 &_0)
    { return ImLengthSqr(_0); }

    float __InlineHelper91(const ImVec4 &_0)
    { return ImLengthSqr(_0); }

    float __InlineHelper92(const ImVec2 &_0, float _1)
    { return ImInvLength(_0, _1); }

    float __InlineHelper93(float _0)
    { return ImFloor(_0); }

    ImVec2 __InlineHelper94(const ImVec2 &_0)
    { return ImFloor(_0); }

    int __InlineHelper95(int _0, int _1)
    { return ImModPositive(_0, _1); }

    float __InlineHelper96(const ImVec2 &_0, const ImVec2 &_1)
    { return ImDot(_0, _1); }

    ImVec2 __InlineHelper97(const ImVec2 &_0, float _1, float _2)
    { return ImRotate(_0, _1, _2); }

    float __InlineHelper98(float _0, float _1, float _2)
    { return ImLinearSweep(_0, _1, _2); }

    ImVec2 __InlineHelper99(const ImVec2 &_0, const ImVec2 &_1)
    { return ImMul(_0, _1); }
#pragma GCC visibility pop
}
