// This file was automatically generated by Biohazrd and should not be modified by hand!
/// <remarks>This type was forward-declared but never defined. Do not dereference.</remarks>
public ref partial struct ID3D11Device
{
}
