// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct ImColor
{
    [FieldOffset(0)] public ImVec4 Value;

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImColor@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImColor* @this);

    public unsafe void Constructor()
    {
        fixed (ImColor* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImColor@@QEAA@HHHH@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImColor* @this, int r, int g, int b, int a);

    public unsafe void Constructor(int r, int g, int b, int a/* = 255 */)
    {
        fixed (ImColor* @this = &this)
        { Constructor_PInvoke(@this, r, g, b, a); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImColor@@QEAA@I@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImColor* @this, uint rgba);

    public unsafe void Constructor(uint rgba)
    {
        fixed (ImColor* @this = &this)
        { Constructor_PInvoke(@this, rgba); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImColor@@QEAA@MMMM@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImColor* @this, float r, float g, float b, float a);

    public unsafe void Constructor(float r, float g, float b, float a/* = 1 */)
    {
        fixed (ImColor* @this = &this)
        { Constructor_PInvoke(@this, r, g, b, a); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImColor@@QEAA@AEBUImVec4@@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImColor* @this, ImVec4* col);

    public unsafe void Constructor(ImVec4* col)
    {
        fixed (ImColor* @this = &this)
        { Constructor_PInvoke(@this, col); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??BImColor@@QEBAIXZ", ExactSpelling = true)]
    private static extern uint ____ConversionOperator_ImU32_PInvoke(ImColor* @this);

    public unsafe uint ____ConversionOperator_ImU32()
    {
        fixed (ImColor* @this = &this)
        { return ____ConversionOperator_ImU32_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??BImColor@@QEBA?AUImVec4@@XZ", ExactSpelling = true)]
    private static extern void ____ConversionOperator_ImVec4_PInvoke(ImColor* @this, out ImVec4 __returnBuffer);

    public unsafe ImVec4 ____ConversionOperator_ImVec4()
    {
        fixed (ImColor* @this = &this)
        {
            ImVec4 __returnBuffer;
            ____ConversionOperator_ImVec4_PInvoke(@this, out __returnBuffer);
            return __returnBuffer;
        }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?SetHSV@ImColor@@QEAAXMMMM@Z", ExactSpelling = true)]
    private static extern void SetHSV_PInvoke(ImColor* @this, float h, float s, float v, float a);

    public unsafe void SetHSV(float h, float s, float v, float a/* = 1 */)
    {
        fixed (ImColor* @this = &this)
        { SetHSV_PInvoke(@this, h, s, v, a); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?HSV@ImColor@@SA?AU1@MMMM@Z", ExactSpelling = true)]
    public static extern void HSV(out ImColor __returnBuffer, float h, float s, float v, float a/* = 1 */);
}
