// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 20)]
public unsafe partial struct ImDrawVert
{
    [FieldOffset(0)] public ImVec2 pos;

    [FieldOffset(8)] public ImVec2 uv;

    [FieldOffset(16)] public uint col;
}
