// This file was automatically generated by Biohazrd and should not be modified by hand!
using System;

[Flags]
public enum ImDrawListFlags
{
    None = 0,
    AntiAliasedLines = 1,
    AntiAliasedLinesUseTex = 2,
    AntiAliasedFill = 4,
    AllowVtxOffset = 8
}
