// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public unsafe partial struct ImDrawData
    {
        [FieldOffset(0)] [MarshalAs(UnmanagedType.I1)] public bool Valid;

        [FieldOffset(4)] public int CmdListsCount;

        [FieldOffset(8)] public int TotalIdxCount;

        [FieldOffset(12)] public int TotalVtxCount;

        [FieldOffset(16)] public ImDrawList** CmdLists;

        [FieldOffset(24)] public ImVec2 DisplayPos;

        [FieldOffset(32)] public ImVec2 DisplaySize;

        [FieldOffset(40)] public ImVec2 FramebufferScale;

        [FieldOffset(48)] public ImGuiViewport* OwnerViewport;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper25", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImDrawData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImDrawData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN10ImDrawData5ClearEv", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImDrawData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImDrawData* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN10ImDrawData17DeIndexAllBuffersEv", ExactSpelling = true)]
        private static extern void DeIndexAllBuffers_PInvoke(ImDrawData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void DeIndexAllBuffers()
        {
            fixed (ImDrawData* @this = &this)
            { DeIndexAllBuffers_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN10ImDrawData14ScaleClipRectsERK6ImVec2", ExactSpelling = true)]
        private static extern void ScaleClipRects_PInvoke(ImDrawData* @this, ImVec2* fb_scale);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ScaleClipRects(ImVec2* fb_scale)
        {
            fixed (ImDrawData* @this = &this)
            { ScaleClipRects_PInvoke(@this, fb_scale); }
        }
    }
}
