// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct ImFontGlyphRangesBuilder
{
    [FieldOffset(0)] public ImVector<uint> UsedChars;

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?AddText@ImFontGlyphRangesBuilder@@QEAAXPEBD0@Z", ExactSpelling = true)]
    private static extern void AddText_PInvoke(ImFontGlyphRangesBuilder* @this, byte* text, byte* text_end);

    [DebuggerStepThrough, DebuggerHidden]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public unsafe void AddText(byte* text, byte* text_end = null)
    {
        fixed (ImFontGlyphRangesBuilder* @this = &this)
        { AddText_PInvoke(@this, text, text_end); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?AddRanges@ImFontGlyphRangesBuilder@@QEAAXPEBG@Z", ExactSpelling = true)]
    private static extern void AddRanges_PInvoke(ImFontGlyphRangesBuilder* @this, ushort* ranges);

    [DebuggerStepThrough, DebuggerHidden]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public unsafe void AddRanges(ushort* ranges)
    {
        fixed (ImFontGlyphRangesBuilder* @this = &this)
        { AddRanges_PInvoke(@this, ranges); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?BuildRanges@ImFontGlyphRangesBuilder@@QEAAXPEAU?$ImVector@G@@@Z", ExactSpelling = true)]
    private static extern void BuildRanges_PInvoke(ImFontGlyphRangesBuilder* @this, ImVector<ushort>* out_ranges);

    [DebuggerStepThrough, DebuggerHidden]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public unsafe void BuildRanges(ImVector<ushort>* out_ranges)
    {
        fixed (ImFontGlyphRangesBuilder* @this = &this)
        { BuildRanges_PInvoke(@this, out_ranges); }
    }
}
