// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImFontAtlasCustomRect
    {
        [FieldOffset(0)] public ushort Width;

        [FieldOffset(2)] public ushort Height;

        [FieldOffset(4)] public ushort X;

        [FieldOffset(6)] public ushort Y;

        [FieldOffset(8)] public uint GlyphID;

        [FieldOffset(12)] public float GlyphAdvanceX;

        [FieldOffset(16)] public ImVec2 GlyphOffset;

        [FieldOffset(24)] public ImFont* Font;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper27", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImFontAtlasCustomRect* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImFontAtlasCustomRect* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK21ImFontAtlasCustomRect8IsPackedEv", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool IsPacked_PInvoke(ImFontAtlasCustomRect* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool IsPacked()
        {
            fixed (ImFontAtlasCustomRect* @this = &this)
            { return IsPacked_PInvoke(@this); }
        }
    }
}
