// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImFontGlyphRangesBuilder
    {
        [FieldOffset(0)] public ImVector<uint> UsedChars;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper26", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImFontGlyphRangesBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN24ImFontGlyphRangesBuilder5ClearEv", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImFontGlyphRangesBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK24ImFontGlyphRangesBuilder6GetBitEm", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool GetBit_PInvoke(ImFontGlyphRangesBuilder* @this, ulong n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool GetBit(ulong n)
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { return GetBit_PInvoke(@this, n); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN24ImFontGlyphRangesBuilder6SetBitEm", ExactSpelling = true)]
        private static extern void SetBit_PInvoke(ImFontGlyphRangesBuilder* @this, ulong n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetBit(ulong n)
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { SetBit_PInvoke(@this, n); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN24ImFontGlyphRangesBuilder7AddCharEt", ExactSpelling = true)]
        private static extern void AddChar_PInvoke(ImFontGlyphRangesBuilder* @this, char c);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void AddChar(char c)
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { AddChar_PInvoke(@this, c); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN24ImFontGlyphRangesBuilder7AddTextEPKcS1_", ExactSpelling = true)]
        private static extern void AddText_PInvoke(ImFontGlyphRangesBuilder* @this, byte* text, byte* text_end);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void AddText(byte* text, byte* text_end = null)
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { AddText_PInvoke(@this, text, text_end); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN24ImFontGlyphRangesBuilder9AddRangesEPKt", ExactSpelling = true)]
        private static extern void AddRanges_PInvoke(ImFontGlyphRangesBuilder* @this, char* ranges);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void AddRanges(char* ranges)
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { AddRanges_PInvoke(@this, ranges); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN24ImFontGlyphRangesBuilder11BuildRangesEP8ImVectorItE", ExactSpelling = true)]
        private static extern void BuildRanges_PInvoke(ImFontGlyphRangesBuilder* @this, ImVector<ushort>* out_ranges);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void BuildRanges(ImVector<ushort>* out_ranges)
        {
            fixed (ImFontGlyphRangesBuilder* @this = &this)
            { BuildRanges_PInvoke(@this, out_ranges); }
        }
    }
}
