// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
public enum ImGuiSortDirection
{
    None = 0,
    Ascending = 1,
    Descending = 2
}
