// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui
{
    public enum ImGuiNavInput
    {
        Activate,
        Cancel,
        Input,
        Menu,
        DpadLeft,
        DpadRight,
        DpadUp,
        DpadDown,
        LStickLeft,
        LStickRight,
        LStickUp,
        LStickDown,
        FocusPrev,
        FocusNext,
        TweakSlow,
        TweakFast,
        KeyMenu_,
        KeyLeft_,
        KeyRight_,
        KeyUp_,
        KeyDown_,
        COUNT,
        InternalStart_ = 16
    }
}
