// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 36)]
public unsafe partial struct ImGuiPlatformMonitor
{
    [FieldOffset(0)] public ImVec2 MainPos;

    [FieldOffset(8)] public ImVec2 MainSize;

    [FieldOffset(16)] public ImVec2 WorkPos;

    [FieldOffset(24)] public ImVec2 WorkSize;

    [FieldOffset(32)] public float DpiScale;
}
