// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public unsafe partial struct ImGuiOnceUponAFrame
    {
        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper8", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiOnceUponAFrame* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (ImGuiOnceUponAFrame* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [FieldOffset(0)] public int RefFrame;

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??BImGuiOnceUponAFrame@@QEBA_NXZ", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool ____ConversionOperator_bool_PInvoke(ImGuiOnceUponAFrame* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe bool ____ConversionOperator_bool()
        {
            fixed (ImGuiOnceUponAFrame* @this = &this)
            { return ____ConversionOperator_bool_PInvoke(@this); }
        }
    }
}
