// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 28)]
public unsafe partial struct ImGuiWindowClass
{
    [FieldOffset(0)] public uint ClassId;

    [FieldOffset(4)] public uint ParentViewportId;

    [FieldOffset(8)] public ImGuiViewportFlags ViewportFlagsOverrideSet;

    [FieldOffset(12)] public ImGuiViewportFlags ViewportFlagsOverrideClear;

    [FieldOffset(16)] public ImGuiDockNodeFlags DockNodeFlagsOverrideSet;

    [FieldOffset(20)] public ImGuiDockNodeFlags DockNodeFlagsOverrideClear;

    [FieldOffset(24)] public bool DockingAlwaysTabBar;

    [FieldOffset(25)] public bool DockingAllowUnclassed;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImGuiWindowClass@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImGuiWindowClass* @this);

    public unsafe void Constructor()
    {
        fixed (ImGuiWindowClass* @this = &this)
        { Constructor_PInvoke(@this); }
    }
}
