// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImGuiStorage
    {
        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public unsafe partial struct ImGuiStoragePair
        {
            [FieldOffset(0)] public uint key;

            [FieldOffset(8)] public int val_i;

            [FieldOffset(8)] public float val_f;

            [FieldOffset(8)] public void* val_p;

            [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper12", ExactSpelling = true)]
            private static extern void Constructor_PInvoke(ImGuiStoragePair* @this, uint _key, int _val_i);

            [DebuggerStepThrough, DebuggerHidden]
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Constructor(uint _key, int _val_i)
            {
                fixed (ImGuiStoragePair* @this = &this)
                { Constructor_PInvoke(@this, _key, _val_i); }
            }

            [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper13", ExactSpelling = true)]
            private static extern void Constructor_PInvoke(ImGuiStoragePair* @this, uint _key, float _val_f);

            [DebuggerStepThrough, DebuggerHidden]
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Constructor(uint _key, float _val_f)
            {
                fixed (ImGuiStoragePair* @this = &this)
                { Constructor_PInvoke(@this, _key, _val_f); }
            }

            [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper14", ExactSpelling = true)]
            private static extern void Constructor_PInvoke(ImGuiStoragePair* @this, uint _key, void* _val_p);

            [DebuggerStepThrough, DebuggerHidden]
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Constructor(uint _key, void* _val_p)
            {
                fixed (ImGuiStoragePair* @this = &this)
                { Constructor_PInvoke(@this, _key, _val_p); }
            }
        }

        [FieldOffset(0)] public ImVector<ImGuiStoragePair> Data;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage5ClearEv", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImGuiStorage* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImGuiStorage* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK12ImGuiStorage6GetIntEji", ExactSpelling = true)]
        private static extern int GetInt_PInvoke(ImGuiStorage* @this, uint key, int default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int GetInt(uint key, int default_val = 0)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetInt_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage6SetIntEji", ExactSpelling = true)]
        private static extern void SetInt_PInvoke(ImGuiStorage* @this, uint key, int val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetInt(uint key, int val)
        {
            fixed (ImGuiStorage* @this = &this)
            { SetInt_PInvoke(@this, key, val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK12ImGuiStorage7GetBoolEjb", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool GetBool_PInvoke(ImGuiStorage* @this, uint key, [MarshalAs(UnmanagedType.I1)] bool default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool GetBool(uint key, bool default_val = false)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetBool_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage7SetBoolEjb", ExactSpelling = true)]
        private static extern void SetBool_PInvoke(ImGuiStorage* @this, uint key, [MarshalAs(UnmanagedType.I1)] bool val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetBool(uint key, bool val)
        {
            fixed (ImGuiStorage* @this = &this)
            { SetBool_PInvoke(@this, key, val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK12ImGuiStorage8GetFloatEjf", ExactSpelling = true)]
        private static extern float GetFloat_PInvoke(ImGuiStorage* @this, uint key, float default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float GetFloat(uint key, float default_val = 0f)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetFloat_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage8SetFloatEjf", ExactSpelling = true)]
        private static extern void SetFloat_PInvoke(ImGuiStorage* @this, uint key, float val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetFloat(uint key, float val)
        {
            fixed (ImGuiStorage* @this = &this)
            { SetFloat_PInvoke(@this, key, val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK12ImGuiStorage10GetVoidPtrEj", ExactSpelling = true)]
        private static extern void* GetVoidPtr_PInvoke(ImGuiStorage* @this, uint key);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void* GetVoidPtr(uint key)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetVoidPtr_PInvoke(@this, key); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage10SetVoidPtrEjPv", ExactSpelling = true)]
        private static extern void SetVoidPtr_PInvoke(ImGuiStorage* @this, uint key, void* val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetVoidPtr(uint key, void* val)
        {
            fixed (ImGuiStorage* @this = &this)
            { SetVoidPtr_PInvoke(@this, key, val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage9GetIntRefEji", ExactSpelling = true)]
        private static extern int* GetIntRef_PInvoke(ImGuiStorage* @this, uint key, int default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int* GetIntRef(uint key, int default_val = 0)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetIntRef_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage10GetBoolRefEjb", ExactSpelling = true)]
        private static extern bool* GetBoolRef_PInvoke(ImGuiStorage* @this, uint key, [MarshalAs(UnmanagedType.I1)] bool default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool* GetBoolRef(uint key, bool default_val = false)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetBoolRef_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage11GetFloatRefEjf", ExactSpelling = true)]
        private static extern float* GetFloatRef_PInvoke(ImGuiStorage* @this, uint key, float default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float* GetFloatRef(uint key, float default_val = 0f)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetFloatRef_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage13GetVoidPtrRefEjPv", ExactSpelling = true)]
        private static extern void** GetVoidPtrRef_PInvoke(ImGuiStorage* @this, uint key, void* default_val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void** GetVoidPtrRef(uint key, void* default_val = null)
        {
            fixed (ImGuiStorage* @this = &this)
            { return GetVoidPtrRef_PInvoke(@this, key, default_val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage9SetAllIntEi", ExactSpelling = true)]
        private static extern void SetAllInt_PInvoke(ImGuiStorage* @this, int val);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetAllInt(int val)
        {
            fixed (ImGuiStorage* @this = &this)
            { SetAllInt_PInvoke(@this, val); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN12ImGuiStorage14BuildSortByKeyEv", ExactSpelling = true)]
        private static extern void BuildSortByKey_PInvoke(ImGuiStorage* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void BuildSortByKey()
        {
            fixed (ImGuiStorage* @this = &this)
            { BuildSortByKey_PInvoke(@this); }
        }
    }
}
