// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 64)]
public unsafe partial struct ImGuiPayload
{
    [FieldOffset(0)] public void* Data;

    [FieldOffset(8)] public int DataSize;

    [FieldOffset(12)] public uint SourceId;

    [FieldOffset(16)] public uint SourceParentId;

    [FieldOffset(20)] public int DataFrameCount;

    [FieldOffset(24)] public ConstantArray_char_33 DataType;

    [FieldOffset(57)] [MarshalAs(UnmanagedType.I1)] public bool Preview;

    [FieldOffset(58)] [MarshalAs(UnmanagedType.I1)] public bool Delivery;

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImGuiPayload@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImGuiPayload* @this);

    public unsafe void Constructor()
    {
        fixed (ImGuiPayload* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Clear@ImGuiPayload@@QEAAXXZ", ExactSpelling = true)]
    private static extern void Clear_PInvoke(ImGuiPayload* @this);

    public unsafe void Clear()
    {
        fixed (ImGuiPayload* @this = &this)
        { Clear_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?IsDataType@ImGuiPayload@@QEBA_NPEBD@Z", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.I1)]
    private static extern bool IsDataType_PInvoke(ImGuiPayload* @this, byte* type);

    public unsafe bool IsDataType(byte* type)
    {
        fixed (ImGuiPayload* @this = &this)
        { return IsDataType_PInvoke(@this, type); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?IsPreview@ImGuiPayload@@QEBA_NXZ", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.I1)]
    private static extern bool IsPreview_PInvoke(ImGuiPayload* @this);

    public unsafe bool IsPreview()
    {
        fixed (ImGuiPayload* @this = &this)
        { return IsPreview_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?IsDelivery@ImGuiPayload@@QEBA_NXZ", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.I1)]
    private static extern bool IsDelivery_PInvoke(ImGuiPayload* @this);

    public unsafe bool IsDelivery()
    {
        fixed (ImGuiPayload* @this = &this)
        { return IsDelivery_PInvoke(@this); }
    }
}
