// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct ImGuiTextBuffer
{
    [FieldOffset(0)] public ImVector<byte> Buf;

    public static readonly ConstantArray_char_1* EmptyString = (ConstantArray_char_1*)NativeLibrary.GetExport(NativeLibrary.Load("TODO.dll"), "?EmptyString@ImGuiTextBuffer@@2PADA");
    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImGuiTextBuffer@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImGuiTextBuffer* @this);

    public unsafe void Constructor()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??AImGuiTextBuffer@@QEBADH@Z", ExactSpelling = true)]
    private static extern byte operator_Subscript_PInvoke(ImGuiTextBuffer* @this, int i);

    public unsafe byte operator_Subscript(int i)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { return operator_Subscript_PInvoke(@this, i); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?begin@ImGuiTextBuffer@@QEBAPEBDXZ", ExactSpelling = true)]
    private static extern byte* begin_PInvoke(ImGuiTextBuffer* @this);

    public unsafe byte* begin()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { return begin_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?end@ImGuiTextBuffer@@QEBAPEBDXZ", ExactSpelling = true)]
    private static extern byte* end_PInvoke(ImGuiTextBuffer* @this);

    public unsafe byte* end()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { return end_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?size@ImGuiTextBuffer@@QEBAHXZ", ExactSpelling = true)]
    private static extern int size_PInvoke(ImGuiTextBuffer* @this);

    public unsafe int size()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { return size_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?empty@ImGuiTextBuffer@@QEBA_NXZ", ExactSpelling = true)]
    private static extern bool empty_PInvoke(ImGuiTextBuffer* @this);

    public unsafe bool empty()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { return empty_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?clear@ImGuiTextBuffer@@QEAAXXZ", ExactSpelling = true)]
    private static extern void clear_PInvoke(ImGuiTextBuffer* @this);

    public unsafe void clear()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { clear_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?reserve@ImGuiTextBuffer@@QEAAXH@Z", ExactSpelling = true)]
    private static extern void reserve_PInvoke(ImGuiTextBuffer* @this, int capacity);

    public unsafe void reserve(int capacity)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { reserve_PInvoke(@this, capacity); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?c_str@ImGuiTextBuffer@@QEBAPEBDXZ", ExactSpelling = true)]
    private static extern byte* c_str_PInvoke(ImGuiTextBuffer* @this);

    public unsafe byte* c_str()
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { return c_str_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?append@ImGuiTextBuffer@@QEAAXPEBD0@Z", ExactSpelling = true)]
    private static extern void append_PInvoke(ImGuiTextBuffer* @this, byte* str, byte* str_end);

    public unsafe void append(byte* str, byte* str_end)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { append_PInvoke(@this, str, str_end); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?appendf@ImGuiTextBuffer@@QEAAXPEBDZZ", ExactSpelling = true)]
    private static extern void appendf_PInvoke(ImGuiTextBuffer* @this, byte* fmt);

    public unsafe void appendf(byte* fmt)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { appendf_PInvoke(@this, fmt); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?appendfv@ImGuiTextBuffer@@QEAAXPEBDPEAD@Z", ExactSpelling = true)]
    private static extern void appendfv_PInvoke(ImGuiTextBuffer* @this, byte* fmt, byte* args);

    public unsafe void appendfv(byte* fmt, byte* args)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { appendfv_PInvoke(@this, fmt, args); }
    }
}
