// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 96)]
public unsafe partial struct ImGuiViewport
{
    [FieldOffset(0)] public uint ID;

    [FieldOffset(4)] public ImGuiViewportFlags Flags;

    [FieldOffset(8)] public ImVec2 Pos;

    [FieldOffset(16)] public ImVec2 Size;

    [FieldOffset(24)] public ImVec2 WorkPos;

    [FieldOffset(32)] public ImVec2 WorkSize;

    [FieldOffset(40)] public float DpiScale;

    [FieldOffset(44)] public uint ParentViewportId;

    [FieldOffset(48)] public ImDrawData* DrawData;

    [FieldOffset(56)] public void* RendererUserData;

    [FieldOffset(64)] public void* PlatformUserData;

    [FieldOffset(72)] public void* PlatformHandle;

    [FieldOffset(80)] public void* PlatformHandleRaw;

    [FieldOffset(88)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestMove;

    [FieldOffset(89)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestResize;

    [FieldOffset(90)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestClose;
}
