// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct ImGuiTextBuffer
{
    [FieldOffset(0)] public ImVector<byte> Buf;

    public static readonly ConstantArray_char_1* EmptyString = (ConstantArray_char_1*)NativeLibrary.GetExport(NativeLibrary.Load("InfectedImGui.Native.dll"), "?EmptyString@ImGuiTextBuffer@@2PADA");

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?append@ImGuiTextBuffer@@QEAAXPEBD0@Z", ExactSpelling = true)]
    private static extern void append_PInvoke(ImGuiTextBuffer* @this, byte* str, byte* str_end);

    [DebuggerStepThrough, DebuggerHidden]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public unsafe void append(byte* str, byte* str_end = null)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { append_PInvoke(@this, str, str_end); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?appendf@ImGuiTextBuffer@@QEAAXPEBDZZ", ExactSpelling = true)]
    private static extern void appendf_PInvoke(ImGuiTextBuffer* @this, byte* fmt);

    [DebuggerStepThrough, DebuggerHidden]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public unsafe void appendf(byte* fmt)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { appendf_PInvoke(@this, fmt); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?appendfv@ImGuiTextBuffer@@QEAAXPEBDPEAD@Z", ExactSpelling = true)]
    private static extern void appendfv_PInvoke(ImGuiTextBuffer* @this, byte* fmt, byte* args);

    [DebuggerStepThrough, DebuggerHidden]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public unsafe void appendfv(byte* fmt, byte* args)
    {
        fixed (ImGuiTextBuffer* @this = &this)
        { appendfv_PInvoke(@this, fmt, args); }
    }
}
