// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 988)]
public unsafe partial struct ImGuiStyle
{
    [FieldOffset(0)] public float Alpha;

    [FieldOffset(4)] public ImVec2 WindowPadding;

    [FieldOffset(12)] public float WindowRounding;

    [FieldOffset(16)] public float WindowBorderSize;

    [FieldOffset(20)] public ImVec2 WindowMinSize;

    [FieldOffset(28)] public ImVec2 WindowTitleAlign;

    [FieldOffset(36)] public int WindowMenuButtonPosition;

    [FieldOffset(40)] public float ChildRounding;

    [FieldOffset(44)] public float ChildBorderSize;

    [FieldOffset(48)] public float PopupRounding;

    [FieldOffset(52)] public float PopupBorderSize;

    [FieldOffset(56)] public ImVec2 FramePadding;

    [FieldOffset(64)] public float FrameRounding;

    [FieldOffset(68)] public float FrameBorderSize;

    [FieldOffset(72)] public ImVec2 ItemSpacing;

    [FieldOffset(80)] public ImVec2 ItemInnerSpacing;

    [FieldOffset(88)] public ImVec2 TouchExtraPadding;

    [FieldOffset(96)] public float IndentSpacing;

    [FieldOffset(100)] public float ColumnsMinSpacing;

    [FieldOffset(104)] public float ScrollbarSize;

    [FieldOffset(108)] public float ScrollbarRounding;

    [FieldOffset(112)] public float GrabMinSize;

    [FieldOffset(116)] public float GrabRounding;

    [FieldOffset(120)] public float LogSliderDeadzone;

    [FieldOffset(124)] public float TabRounding;

    [FieldOffset(128)] public float TabBorderSize;

    [FieldOffset(132)] public float TabMinWidthForCloseButton;

    [FieldOffset(136)] public int ColorButtonPosition;

    [FieldOffset(140)] public ImVec2 ButtonTextAlign;

    [FieldOffset(148)] public ImVec2 SelectableTextAlign;

    [FieldOffset(156)] public ImVec2 DisplayWindowPadding;

    [FieldOffset(164)] public ImVec2 DisplaySafeAreaPadding;

    [FieldOffset(172)] public float MouseCursorScale;

    [FieldOffset(176)] public bool AntiAliasedLines;

    [FieldOffset(177)] public bool AntiAliasedLinesUseTex;

    [FieldOffset(178)] public bool AntiAliasedFill;

    [FieldOffset(180)] public float CurveTessellationTol;

    [FieldOffset(184)] public float CircleSegmentMaxError;

    [FieldOffset(188)] public ConstantArray_ImVec4_50 Colors;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImGuiStyle@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImGuiStyle* @this);

    public unsafe void Constructor()
    {
        fixed (ImGuiStyle* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?ScaleAllSizes@ImGuiStyle@@QEAAXM@Z", ExactSpelling = true)]
    private static extern void ScaleAllSizes_PInvoke(ImGuiStyle* @this, float scale_factor);

    public unsafe void ScaleAllSizes(float scale_factor)
    {
        fixed (ImGuiStyle* @this = &this)
        { ScaleAllSizes_PInvoke(@this, scale_factor); }
    }
}
