// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 96)]
    public unsafe partial struct ImGuiViewport
    {
        [FieldOffset(0)] public uint ID;

        [FieldOffset(4)] public ImGuiViewportFlags Flags;

        [FieldOffset(8)] public ImVec2 Pos;

        [FieldOffset(16)] public ImVec2 Size;

        [FieldOffset(24)] public ImVec2 WorkPos;

        [FieldOffset(32)] public ImVec2 WorkSize;

        [FieldOffset(40)] public float DpiScale;

        [FieldOffset(44)] public uint ParentViewportId;

        [FieldOffset(48)] public ImDrawData* DrawData;

        [FieldOffset(56)] public void* RendererUserData;

        [FieldOffset(64)] public void* PlatformUserData;

        [FieldOffset(72)] public void* PlatformHandle;

        [FieldOffset(80)] public void* PlatformHandleRaw;

        [FieldOffset(88)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestMove;

        [FieldOffset(89)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestResize;

        [FieldOffset(90)] [MarshalAs(UnmanagedType.I1)] public bool PlatformRequestClose;

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper28", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiViewport* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (ImGuiViewport* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper29", ExactSpelling = true)]
        private static extern void Destructor_PInvoke(ImGuiViewport* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Destructor()
        {
            fixed (ImGuiViewport* @this = &this)
            { Destructor_PInvoke(@this); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetCenter@ImGuiViewport@@QEBA?AUImVec2@@XZ", ExactSpelling = true)]
        private static extern ImVec2* GetCenter_PInvoke(ImGuiViewport* @this, out ImVec2 __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe ImVec2 GetCenter()
        {
            fixed (ImGuiViewport* @this = &this)
            {
                ImVec2 __returnBuffer;
                GetCenter_PInvoke(@this, out __returnBuffer);
                return __returnBuffer;
            }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?GetWorkCenter@ImGuiViewport@@QEBA?AUImVec2@@XZ", ExactSpelling = true)]
        private static extern ImVec2* GetWorkCenter_PInvoke(ImGuiViewport* @this, out ImVec2 __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe ImVec2 GetWorkCenter()
        {
            fixed (ImGuiViewport* @this = &this)
            {
                ImVec2 __returnBuffer;
                GetWorkCenter_PInvoke(@this, out __returnBuffer);
                return __returnBuffer;
            }
        }
    }
}
