// This file was automatically generated by Biohazrd and should not be modified by hand!
public enum ImGuiMouseCursor
{
    None = -1,
    Arrow = 0,
    TextInput,
    ResizeAll,
    ResizeNS,
    ResizeEW,
    ResizeNESW,
    ResizeNWSE,
    Hand,
    NotAllowed,
    COUNT,
    Count_ = 9
}
