// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 64)]
public unsafe partial struct ImGuiPayload
{
    [FieldOffset(0)] public void* Data;

    [FieldOffset(8)] public int DataSize;

    [FieldOffset(12)] public uint SourceId;

    [FieldOffset(16)] public uint SourceParentId;

    [FieldOffset(20)] public int DataFrameCount;

    [FieldOffset(24)] public ConstantArray_char_33 DataType;

    [FieldOffset(57)] [MarshalAs(UnmanagedType.I1)] public bool Preview;

    [FieldOffset(58)] [MarshalAs(UnmanagedType.I1)] public bool Delivery;
}
