// This file was automatically generated by Biohazrd and should not be modified by hand!
using System;

[Flags]
public enum ImGuiComboFlags
{
    None = 0,
    PopupAlignLeft = 1,
    HeightSmall = 2,
    HeightRegular = 4,
    HeightLarge = 8,
    HeightLargest = 16,
    NoArrowButton = 32,
    NoPreview = 64,
    HeightMask_ = 30
}
