// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui
{
    [StructLayout(LayoutKind.Explicit, Size = 28)]
    public unsafe partial struct ImGuiListClipper
    {
        [FieldOffset(0)] public int DisplayStart;

        [FieldOffset(4)] public int DisplayEnd;

        [FieldOffset(8)] public int ItemsCount;

        [FieldOffset(12)] public int StepNo;

        [FieldOffset(16)] public int ItemsFrozen;

        [FieldOffset(20)] public float ItemsHeight;

        [FieldOffset(24)] public float StartPosY;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiListClipperC1Ev", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiListClipper* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImGuiListClipper* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiListClipperD2Ev", ExactSpelling = true)]
        private static extern void Destructor_PInvoke(ImGuiListClipper* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (ImGuiListClipper* @this = &this)
            { Destructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiListClipper5BeginEif", ExactSpelling = true)]
        private static extern void Begin_PInvoke(ImGuiListClipper* @this, int items_count, float items_height);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Begin(int items_count, float items_height = -1f)
        {
            fixed (ImGuiListClipper* @this = &this)
            { Begin_PInvoke(@this, items_count, items_height); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiListClipper3EndEv", ExactSpelling = true)]
        private static extern void End_PInvoke(ImGuiListClipper* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void End()
        {
            fixed (ImGuiListClipper* @this = &this)
            { End_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiListClipper4StepEv", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool Step_PInvoke(ImGuiListClipper* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Step()
        {
            fixed (ImGuiListClipper* @this = &this)
            { return Step_PInvoke(@this); }
        }
    }
}
