// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct ImGuiTableSortSpecs
{
    [FieldOffset(0)] public ImGuiTableColumnSortSpecs* Specs;

    [FieldOffset(8)] public int SpecsCount;

    [FieldOffset(12)] [MarshalAs(UnmanagedType.I1)] public bool SpecsDirty;
}
