// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.ComponentModel;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct ImVec2
{
    [FieldOffset(0)] public float x;

    [FieldOffset(4)] public float y;

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImVec2@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImVec2* @this);

    public unsafe void Constructor()
    {
        fixed (ImVec2* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0ImVec2@@QEAA@MM@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(ImVec2* @this, float _x, float _y);

    public unsafe void Constructor(float _x, float _y)
    {
        fixed (ImVec2* @this = &this)
        { Constructor_PInvoke(@this, _x, _y); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??AImVec2@@QEBAM_K@Z", ExactSpelling = true)]
    private static extern float operator_Subscript_Const_PInvoke(ImVec2* @this, ulong idx);

    [EditorBrowsable(EditorBrowsableState.Never)]
    public unsafe float operator_Subscript_Const(ulong idx)
    {
        fixed (ImVec2* @this = &this)
        { return operator_Subscript_Const_PInvoke(@this, idx); }
    }

    [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??AImVec2@@QEAAAEAM_K@Z", ExactSpelling = true)]
    private static extern float* operator_Subscript_PInvoke(ImVec2* @this, ulong idx);

    public unsafe float* operator_Subscript(ulong idx)
    {
        fixed (ImVec2* @this = &this)
        { return operator_Subscript_PInvoke(@this, idx); }
    }
}
