// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct ImVec4
{
    [FieldOffset(0)] public float x;

    [FieldOffset(4)] public float y;

    [FieldOffset(8)] public float z;

    [FieldOffset(12)] public float w;
}
