// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Backends.Direct3D11
{
    /// <remarks>This type was forward-declared but never defined. Do not dereference.</remarks>
    public ref partial struct ID3D11DeviceContext
    {
    }
}
