// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImBitVector
    {
        [FieldOffset(0)] public ImVector<uint> Storage;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN11ImBitVector6CreateEi", ExactSpelling = true)]
        private static extern void Create_PInvoke(ImBitVector* @this, int sz);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Create(int sz)
        {
            fixed (ImBitVector* @this = &this)
            { Create_PInvoke(@this, sz); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN11ImBitVector5ClearEv", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImBitVector* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImBitVector* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK11ImBitVector7TestBitEi", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool TestBit_PInvoke(ImBitVector* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool TestBit(int n)
        {
            fixed (ImBitVector* @this = &this)
            { return TestBit_PInvoke(@this, n); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN11ImBitVector6SetBitEi", ExactSpelling = true)]
        private static extern void SetBit_PInvoke(ImBitVector* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetBit(int n)
        {
            fixed (ImBitVector* @this = &this)
            { SetBit_PInvoke(@this, n); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN11ImBitVector8ClearBitEi", ExactSpelling = true)]
        private static extern void ClearBit_PInvoke(ImBitVector* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ClearBit(int n)
        {
            fixed (ImBitVector* @this = &this)
            { ClearBit_PInvoke(@this, n); }
        }
    }
}
