// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct ImBitVector
    {
        [FieldOffset(0)] public ImVector<uint> Storage;

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Create@ImBitVector@@QEAAXH@Z", ExactSpelling = true)]
        private static extern void Create_PInvoke(ImBitVector* @this, int sz);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Create(int sz)
        {
            fixed (ImBitVector* @this = &this)
            { Create_PInvoke(@this, sz); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Clear@ImBitVector@@QEAAXXZ", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImBitVector* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Clear()
        {
            fixed (ImBitVector* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?TestBit@ImBitVector@@QEBA_NH@Z", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool TestBit_PInvoke(ImBitVector* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe bool TestBit(int n)
        {
            fixed (ImBitVector* @this = &this)
            { return TestBit_PInvoke(@this, n); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?SetBit@ImBitVector@@QEAAXH@Z", ExactSpelling = true)]
        private static extern void SetBit_PInvoke(ImBitVector* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void SetBit(int n)
        {
            fixed (ImBitVector* @this = &this)
            { SetBit_PInvoke(@this, n); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?ClearBit@ImBitVector@@QEAAXH@Z", ExactSpelling = true)]
        private static extern void ClearBit_PInvoke(ImBitVector* @this, int n);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void ClearBit(int n)
        {
            fixed (ImBitVector* @this = &this)
            { ClearBit_PInvoke(@this, n); }
        }
    }
}
