// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using InfectedImGui.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImDrawDataBuilder
    {
        [FieldOffset(0)] public ConstantArray_ImVector__UNICODE_003C__ImDrawList__UNICODE_0020____UNICODE_002A____UNICODE_003E___2 Layers;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN17ImDrawDataBuilder5ClearEv", ExactSpelling = true)]
        private static extern void Clear_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { Clear_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN17ImDrawDataBuilder15ClearFreeMemoryEv", ExactSpelling = true)]
        private static extern void ClearFreeMemory_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ClearFreeMemory()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { ClearFreeMemory_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK17ImDrawDataBuilder16GetDrawListCountEv", ExactSpelling = true)]
        private static extern int GetDrawListCount_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public int GetDrawListCount()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { return GetDrawListCount_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN17ImDrawDataBuilder22FlattenIntoSingleLayerEv", ExactSpelling = true)]
        private static extern void FlattenIntoSingleLayer_PInvoke(ImDrawDataBuilder* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void FlattenIntoSingleLayer()
        {
            fixed (ImDrawDataBuilder* @this = &this)
            { FlattenIntoSingleLayer_PInvoke(@this); }
        }
    }
}
