// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiLogType : uint
    {
        ImGuiLogType_None = 0,
        ImGuiLogType_TTY,
        ImGuiLogType_File,
        ImGuiLogType_Buffer,
        ImGuiLogType_Clipboard
    }
}
