// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public unsafe partial struct ImGuiNextItemData
    {
        [FieldOffset(0)] public ImGuiNextItemDataFlags Flags;

        [FieldOffset(4)] public float Width;

        [FieldOffset(8)] public uint FocusScopeId;

        [FieldOffset(12)] public ImGuiCond OpenCond;

        [FieldOffset(16)] [MarshalAs(UnmanagedType.I1)] public bool OpenVal;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper49", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiNextItemData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImGuiNextItemData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN17ImGuiNextItemData10ClearFlagsEv", ExactSpelling = true)]
        private static extern void ClearFlags_PInvoke(ImGuiNextItemData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ClearFlags()
        {
            fixed (ImGuiNextItemData* @this = &this)
            { ClearFlags_PInvoke(@this); }
        }
    }
}
