// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImGuiContextHook
    {
        [FieldOffset(0)] public uint HookId;

        [FieldOffset(4)] public ImGuiContextHookType Type;

        [FieldOffset(8)] public uint Owner;

        [FieldOffset(16)] public delegate* unmanaged[Cdecl]<ImGuiContext*, ImGuiContextHook*, void> Callback;

        [FieldOffset(24)] public void* UserData;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper61", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiContextHook* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImGuiContextHook* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
