// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace InfectedImGui.Internal
{
    [Flags]
    public enum ImGuiSeparatorFlags
    {
        None = 0,
        Horizontal = 1,
        Vertical = 2,
        SpanAllColumns = 4
    }
}
