// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public unsafe partial struct ImGuiLastItemDataBackup
    {
        [FieldOffset(0)] public uint LastItemId;

        [FieldOffset(4)] public ImGuiItemStatusFlags LastItemStatusFlags;

        [FieldOffset(8)] public ImRect LastItemRect;

        [FieldOffset(24)] public ImRect LastItemDisplayRect;

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper63", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiLastItemDataBackup* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (ImGuiLastItemDataBackup* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Backup@ImGuiLastItemDataBackup@@QEAAXXZ", ExactSpelling = true)]
        private static extern void Backup_PInvoke(ImGuiLastItemDataBackup* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Backup()
        {
            fixed (ImGuiLastItemDataBackup* @this = &this)
            { Backup_PInvoke(@this); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?Restore@ImGuiLastItemDataBackup@@QEBAXXZ", ExactSpelling = true)]
        private static extern void Restore_PInvoke(ImGuiLastItemDataBackup* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Restore()
        {
            fixed (ImGuiLastItemDataBackup* @this = &this)
            { Restore_PInvoke(@this); }
        }
    }
}
