// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using InfectedImGui.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 304)]
    public unsafe partial struct ImGuiViewportP
    {
        [FieldOffset(0)] public ImGuiViewport Base;

        [FieldOffset(92)] public int Idx;

        [FieldOffset(96)] public int LastFrameActive;

        [FieldOffset(100)] public int LastFrontMostStampCount;

        [FieldOffset(104)] public uint LastNameHash;

        [FieldOffset(108)] public ImVec2 LastPos;

        [FieldOffset(116)] public float Alpha;

        [FieldOffset(120)] public float LastAlpha;

        [FieldOffset(124)] public short PlatformMonitor;

        [FieldOffset(126)] [MarshalAs(UnmanagedType.I1)] public bool PlatformWindowCreated;

        [FieldOffset(128)] public ImGuiWindow* Window;

        [FieldOffset(136)] public ConstantArray_int_2 DrawListsLastFrame;

        [FieldOffset(144)] public ConstantArray_ImDrawList__UNICODE_0020____UNICODE_002A___2 DrawLists;

        [FieldOffset(160)] public ImDrawData DrawDataP;

        [FieldOffset(216)] public ImDrawDataBuilder DrawDataBuilder;

        [FieldOffset(248)] public ImVec2 LastPlatformPos;

        [FieldOffset(256)] public ImVec2 LastPlatformSize;

        [FieldOffset(264)] public ImVec2 LastRendererSize;

        [FieldOffset(272)] public ImVec2 WorkOffsetMin;

        [FieldOffset(280)] public ImVec2 WorkOffsetMax;

        [FieldOffset(288)] public ImVec2 CurrWorkOffsetMin;

        [FieldOffset(296)] public ImVec2 CurrWorkOffsetMax;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper55", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiViewportP* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImGuiViewportP* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper56", ExactSpelling = true)]
        private static extern void Destructor_PInvoke(ImGuiViewportP* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (ImGuiViewportP* @this = &this)
            { Destructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK14ImGuiViewportP11GetMainRectEv", ExactSpelling = true)]
        private static extern ImRect GetMainRect_PInvoke(ImGuiViewportP* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImRect GetMainRect()
        {
            fixed (ImGuiViewportP* @this = &this)
            { return GetMainRect_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK14ImGuiViewportP11GetWorkRectEv", ExactSpelling = true)]
        private static extern ImRect GetWorkRect_PInvoke(ImGuiViewportP* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ImRect GetWorkRect()
        {
            fixed (ImGuiViewportP* @this = &this)
            { return GetWorkRect_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN14ImGuiViewportP14UpdateWorkRectEv", ExactSpelling = true)]
        private static extern void UpdateWorkRect_PInvoke(ImGuiViewportP* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void UpdateWorkRect()
        {
            fixed (ImGuiViewportP* @this = &this)
            { UpdateWorkRect_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN14ImGuiViewportP17ClearRequestFlagsEv", ExactSpelling = true)]
        private static extern void ClearRequestFlags_PInvoke(ImGuiViewportP* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void ClearRequestFlags()
        {
            fixed (ImGuiViewportP* @this = &this)
            { ClearRequestFlags_PInvoke(@this); }
        }
    }
}
