// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct ImGuiDataTypeInfo
    {
        [FieldOffset(0)] public ulong Size;

        [FieldOffset(8)] public byte* Name;

        [FieldOffset(16)] public byte* PrintFmt;

        [FieldOffset(24)] public byte* ScanFmt;
    }
}
