// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiLayoutType
    {
        Horizontal = 0,
        Vertical = 1
    }
}
