// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiDockNodeFlagsPrivate_
    {
        ImGuiDockNodeFlags_DockSpace = 1024,
        ImGuiDockNodeFlags_CentralNode = 2048,
        ImGuiDockNodeFlags_NoTabBar = 4096,
        ImGuiDockNodeFlags_HiddenTabBar = 8192,
        ImGuiDockNodeFlags_NoWindowMenuButton = 16384,
        ImGuiDockNodeFlags_NoCloseButton = 32768,
        ImGuiDockNodeFlags_NoDocking = 65536,
        ImGuiDockNodeFlags_NoDockingSplitMe = 131072,
        ImGuiDockNodeFlags_NoDockingSplitOther = 262144,
        ImGuiDockNodeFlags_NoDockingOverMe = 524288,
        ImGuiDockNodeFlags_NoDockingOverOther = 1048576,
        ImGuiDockNodeFlags_NoResizeX = 2097152,
        ImGuiDockNodeFlags_NoResizeY = 4194304,
        ImGuiDockNodeFlags_SharedFlagsInheritMask_ = -1,
        ImGuiDockNodeFlags_NoResizeFlagsMask_ = 6291488,
        ImGuiDockNodeFlags_LocalFlagsMask_ = 6421616,
        ImGuiDockNodeFlags_LocalFlagsTransferMask_ = 6420592,
        ImGuiDockNodeFlags_SavedFlagsMask_ = 6421536
    }
}
