// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiDataTypePrivate_ : uint
    {
        ImGuiDataType_String = 11,
        ImGuiDataType_Pointer,
        ImGuiDataType_ID
    }
}
