// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using InfectedImGui.Infrastructure;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public unsafe partial struct ImGuiWindowDockStyle
    {
        [FieldOffset(0)] public ConstantArray_ImU32_6 Colors;
    }
}
