// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using InfectedImGui.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 36)]
    public unsafe partial struct ImGuiMenuColumns
    {
        [FieldOffset(0)] public float Spacing;

        [FieldOffset(4)] public float Width;

        [FieldOffset(8)] public float NextWidth;

        [FieldOffset(12)] public ConstantArray_float_3 Pos;

        [FieldOffset(24)] public ConstantArray_float_3 NextWidths;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper44", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiMenuColumns* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (ImGuiMenuColumns* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiMenuColumns6UpdateEifb", ExactSpelling = true)]
        private static extern void Update_PInvoke(ImGuiMenuColumns* @this, int count, float spacing, [MarshalAs(UnmanagedType.I1)] bool clear);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Update(int count, float spacing, bool clear)
        {
            fixed (ImGuiMenuColumns* @this = &this)
            { Update_PInvoke(@this, count, spacing, clear); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZN16ImGuiMenuColumns11DeclColumnsEfff", ExactSpelling = true)]
        private static extern float DeclColumns_PInvoke(ImGuiMenuColumns* @this, float w0, float w1, float w2);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float DeclColumns(float w0, float w1, float w2)
        {
            fixed (ImGuiMenuColumns* @this = &this)
            { return DeclColumns_PInvoke(@this, w0, w1, w2); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "_ZNK16ImGuiMenuColumns14CalcExtraSpaceEf", ExactSpelling = true)]
        private static extern float CalcExtraSpace_PInvoke(ImGuiMenuColumns* @this, float avail_w);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public float CalcExtraSpace(float avail_w)
        {
            fixed (ImGuiMenuColumns* @this = &this)
            { return CalcExtraSpace_PInvoke(@this, avail_w); }
        }
    }
}
