// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiSelectableFlagsPrivate_ : uint
    {
        ImGuiSelectableFlags_NoHoldingActiveID = 1048576,
        ImGuiSelectableFlags_SelectOnClick = 2097152,
        ImGuiSelectableFlags_SelectOnRelease = 4194304,
        ImGuiSelectableFlags_SpanAvailWidth = 8388608,
        ImGuiSelectableFlags_DrawHoveredWhenHeld = 16777216,
        ImGuiSelectableFlags_SetNavIdOnHover = 33554432,
        ImGuiSelectableFlags_NoPadWithHalfSpacing = 67108864
    }
}
