// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using InfectedImGui.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public unsafe partial struct ImGuiStyleMod
    {
        [FieldOffset(0)] public ImGuiStyleVar VarIdx;

        [FieldOffset(4)] public ConstantArray_int_2 BackupInt;

        [FieldOffset(4)] public ConstantArray_float_2 BackupFloat;

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper41", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStyleMod* @this, ImGuiStyleVar idx, int v);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor(ImGuiStyleVar idx, int v)
        {
            fixed (ImGuiStyleMod* @this = &this)
            { Constructor_PInvoke(@this, idx, v); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper42", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStyleMod* @this, ImGuiStyleVar idx, float v);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor(ImGuiStyleVar idx, float v)
        {
            fixed (ImGuiStyleMod* @this = &this)
            { Constructor_PInvoke(@this, idx, v); }
        }

        [DllImport("libInfectedImGui.Native.so", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper43", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiStyleMod* @this, ImGuiStyleVar idx, ImVec2 v);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor(ImGuiStyleVar idx, ImVec2 v)
        {
            fixed (ImGuiStyleMod* @this = &this)
            { Constructor_PInvoke(@this, idx, v); }
        }
    }
}
