// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct ImGuiTableCellData
    {
        [FieldOffset(0)] public uint BgColor;

        [FieldOffset(4)] public sbyte Column;
    }
}
