// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public unsafe partial struct ImGuiDockContext
    {
        [FieldOffset(0)] public ImGuiStorage Nodes;

        [FieldOffset(48)] [MarshalAs(UnmanagedType.I1)] public bool WantFullRebuild;

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper54", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImGuiDockContext* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (ImGuiDockContext* @this = &this)
            { Constructor_PInvoke(@this); }
        }
    }
}
