// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiTabItemFlagsPrivate_ : uint
    {
        ImGuiTabItemFlags_NoCloseButton = 1048576,
        ImGuiTabItemFlags_Button = 2097152,
        ImGuiTabItemFlags_Unsorted = 4194304,
        ImGuiTabItemFlags_Preview = 8388608
    }
}
