// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace InfectedImGui.Internal
{
    public enum ImGuiInputSource : uint
    {
        ImGuiInputSource_None = 0,
        ImGuiInputSource_Mouse,
        ImGuiInputSource_Nav,
        ImGuiInputSource_NavKeyboard,
        ImGuiInputSource_NavGamepad,
        ImGuiInputSource_COUNT
    }
}
