// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace InfectedImGui.Internal
{
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public unsafe partial struct ImVec2ih
    {
        [FieldOffset(0)] public short x;

        [FieldOffset(2)] public short y;

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper34", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImVec2ih* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (ImVec2ih* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper35", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImVec2ih* @this, short _x, short _y);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(short _x, short _y)
        {
            fixed (ImVec2ih* @this = &this)
            { Constructor_PInvoke(@this, _x, _y); }
        }

        [DllImport("InfectedImGui.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper36", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(ImVec2ih* @this, ImVec2* rhs);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(ImVec2* rhs)
        {
            fixed (ImVec2ih* @this = &this)
            { Constructor_PInvoke(@this, rhs); }
        }
    }
}
